config/routes.rb
Rails.application.routes.draw do
  get 'reviews/index'

  resources :restaurants do
    resources :reviews #, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: { in: CATEGORIES, allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  RATINGS = (0..5).to_a

  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: true, inclusion: { in: RATINGS, allow_nil: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def update
    @restaurant.update(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(reviews_params)

    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def set_restaurant
   @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def reviews_params
   params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">

    <%= simple_form_for @restaurant do |f| %>
    <%= f.error_notification %>

    <%= f.input :name %>

    <%= f.input :address %>

    <%= f.input :phone_number %>

     <%= f.input :category, as: :select, collection: Restaurant::CATEGORIES  %>

    <%= f.submit %>

    <% end %>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h2>Edit:</h2>
<%= render "form" %>
<%= link_to "Cancel Edit", restaurant_path(@restaurant)%>

app/views/restaurants/index.html.erb
<div class="row">
  <%= link_to "Add Restaurant", "/restaurants/new", style: "float: right; margin: 0px;" %>
</div>

<h2>Restaurants</h2>


<div class="container">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
    <div class="col-xs-12 col-sm-4" style="padding: 10px;">
      <div class="card">
        <div class="card-category"><%= restaurant.category.capitalize %></div>
        <div class="card-description">
          <h3><%= link_to restaurant.name, restaurant_path(restaurant.id) %></h3>
          <h2><%= restaurant.phone_number %></h2>
          <p><%= restaurant.address %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>
<%= render "form" %>
<%= link_to "Cancel Creation", restaurants_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h1>
<h3><%= @restaurant.address %></h4>
<h3><%= @restaurant.phone_number %></h4>
<h3><%= @restaurant.category.capitalize %></h4>


<h2>Reviews:</h2>
<% @restaurant.reviews.each do |review| %>
  <p><%= review.content %> : <%= review.rating %></p>
<% end %>

<%= link_to "Add Review", new_restaurant_review_path(@restaurant) %> <br>
<%= link_to "Edit the Restaurant", edit_restaurant_path(@restaurant) %> <br>
<%= link_to "Delete the Restaurant", restaurant_path(@restaurant), method: :delete %> <br>
<%= link_to "List Restaurants", restaurants_path %>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<%= @restaurant.name %>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">

    <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.error_notification %>

    <%= f.input :content %>

    <%= f.input :rating, as: :select, collection: Review::RATINGS  %>

    <%= f.submit %>

    <% end %>
    <%= link_to "Cancel Creation", restaurants_path %>
  </div>
</div>